### ISSUE TITLE
What does dfs_filter do and what's the intention to use it?

### ISSUE THREAD

**Issue by zhxt95** [Featuretools/featuretools#127]
I find that the `traversal filter` has been used in dfs while recursively building forward and backward dfs. But I don't understand what this filter really do and I haven't find any docs or annotation that explained it. 
It seems like this filter makes some check on entity's variable count and unique_percent, which is confusing to me. Why do we need to do  this kind of check in recursively building dfs steps?
And there is another filter `LimitModeUniques` in dfs_filter.py which is also imported in dfs but seems not to be used. Is there any plan to use that filter in the future?
Thx for reading my long questions and looking forward to your reply!

**Comment by kmax12** [comment]
The idea behind DFS filters was to write rules that control (1) the exploration of entities (e.g `TraverseUp`) and the creation of features (e.g `LimitModeUniques`) using plugin architecture. Since implementing it we haven't used it extensively or made it available to end users. It should be thought of as an internal implementation detail.

We may refactor in future, but such work wouldn't impact our public API. If you're interested in chatting more, we can use the Featuretools gitter gitter.im/featuretools/featuretools
