### ISSUE TITLE
Integer column names in dataframe

### ISSUE THREAD

**Issue by Seth-Rothschild** [Featuretools/featuretools#254]
### Bug Description
Currently, if your dataframe has an integer column name, running `es.entity_from_dataframe` will throw an error. There are three ways we might consider dealing with this:
1. We convert non-strings to strings automatically 
2. We detect the existence of non-strings and raise an error with a message for how to fix
3. We natively support integers. This is challenging, because we'll have to support integers when generating feature names in primitive stacking as well.

Of these, there are arguments for both 1 and 2. I'd lean towards 2 because it encourages the better result: if you have named columns the features generated will be easier to parse. 

Thanks to @WacoHolve_gitlab on gitter for finding this issue and providing a MWE there.

-----
*Issues created here on Github are for bugs or feature requests. For usage questions and questions about errors, please ask on Stack Overflow with the [featuretools](https://stackoverflow.com/questions/tagged/featuretools) tag. Check the [documentation](https://docs.featuretools.com/#get-help) for further guidance on where to ask your question.*

**Comment by kmax12** [comment]
I vote for option 2 for simplicity. In general, my experience found that automatically cleaning input automatically data is great when it works, but when stuff goes wrong it becomes very confusing for end users. For example, if we convert automatically, people might become confused when the feature in the returned dataframe is a string instead of `int` that they passed in. 

I realize this is hypocritical because we already do some inference of pandas dtypes, but it on the roadmap to remove many of those inferences from featuretools.
