### ISSUE TITLE
DFS errors by stacking on expanding features

### ISSUE THREAD

**Issue by bschreck** [Featuretools/featuretools#85]
Supplying the NMostCommon and NUnique features to DFS errors, as it stacks NUnique on NMostCommon, which is an expanding feature that returns lists as output. The resulting values supplied to NUnique look like:
```
pd.Series([['v1', 'v2', v3'], ['v2, 'v3', 'v1']])
```
We don't have a good way of handling the stacking of expanding features in pandas_backend, so instead we should just not allow them in DFS.

**Comment by Seth-Rothschild** [comment]
So right now `NUnique` takes `[Discrete]` as input and `NMostCommon` outputs `Discrete`. It might be reasonable to define a new type that more accurately describes either the input of `NUnique` or the output of `NMostCommon` instead of restricting the stacking directly. 

It seems like otherwise this could come up again, so we'd have to explicitly denote a subset of `Discrete` types that's no good for certain primitives. That's problematic because it undercuts the core benefit of having fixed input and output types.

**Comment by bschreck** [comment]
I agree in theory, but it wouldn't come up again for any feature that has the "expanding" attribute set to True. Instead of expanding, it might make more sense to have something like a ListDiscrete and ListNumeric type.

**Comment by Seth-Rothschild** [comment]
Closing via #238 which does exactly what you initially proposed to prevent things from breaking.

Using a ListVariable type still seems like a reasonable thing to do since it's easy to imagine primitives which would want to take in a series of lists.
